export const STATES_IVE_VISITED = [
  // "Alabama",
  "Alaska",
  "Arizona",
  // "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  // "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  // "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  // "North Carolina",
  // "North Dakota",
  "Ohio",
  // "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  // "South Carolina",
  // "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const CHINESE_PROVINCES = [
  "香港",
  "上海",
  "天津",
  "北京",
  "重庆",
  "河北",
  "山西",
  "黑龙江",
  "海南",
  "江苏",
  "浙江",
  "安徽",
  "山西",
  "山东",
  "湖北",
  "河北",
  "湖南",
  "广东",
  "陕西",
  "云南",
  "四川",
  "内蒙古",
  "河南",
];

export const COUNTRIES = [
  "AUS",
  "NZL", // Oceania
  "CAN",
  "MEX",
  "CUB",
  "VIR",
  "PAN",
  "SLV",
  "BHS",
  "PRI", // NA
  "AUT",
  "BEL",
  "CZE",
  "DNK",
  "FRA",
  "DEU",
  "GRC",
  "ISL",
  "LUX",
  "NLD",
  "GBR",
  "HUN",
  "SVK",
  "SVN",
  "ESP",
  "SWE",
  "CHE",
  "POL",
  "ITA",
  "VAT",
  "CYP", // Europe
  "ARG",
  "BOL",
  "ECU",
  "BRA",
  "CHL",
  "PER", // South America
  "EGY",
  "KEN", // Africa
  "GUM",
  "HKG",
  "JPN",
  "KOR",
  "TWN",
  "THA",
  "TUR",
  "VNM",
  "MYS",
  "KHM",
  "PHL", // Asia
];

export const highlightColor = "#6f7040";

export const LOCATIONS: {
  longitude: number;
  latitude: number;
  name: string;
}[] = [
  { latitude: 37.773972, longitude: -122.431297, name: "San Francisco" },
  { latitude: 42.361145, longitude: -71.057083, name: "Boston" },
  { latitude: 40.7127837, longitude: -74.0059413, name: "New York" },
  { latitude: 35.652832, longitude: 139.839478, name: "Tokyo" },
  { latitude: 39.916668, longitude: 116.390625, name: "Beijing" },
  { latitude: 22.3193, longitude: 114.1694, name: "Hong Kong" },
  { latitude: -33.447487, longitude: -70.669267, name: "Santiago" },
  { latitude: 49.24966, longitude: -123.11934, name: "Vancouver" },
  { latitude: 45.523064, longitude: -122.676483, name: "Portland" },
  { latitude: 52.520008, longitude: 13.404954, name: "Berlin" },
  { latitude: 19.941445, longitude: -155.792655, name: "Hawaii" },
];
